version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      
  app:
    build:
      context: .
      args:
        JAR_FILE: ./target/demo-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    environment:
      DB_HOST: db
      # to choose a different application properties file
      # here's the not-so-hackish-hack https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-set-active-spring-profiles
      SPRING_PROFILES_ACTIVE: PROD
